pipelines:
  default:
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --mirror https://x-token-auth:"$BITBUCKETS_VARIABLE"@bitbucket.org/neilly_bucket2/bit-git.git ## @bitbucket.org follow by your Bitbucket repository path
            - cd bit-git.git ## cd followed by your Github repository Name
            - git push --mirror https://x-token-auth:"$GITHUB_VARIABLE"@github.com/neil-amstrong/Mirroring-Repo.git ## @github.com followed by your Github repository path

